// The stone-and-gold theme's colours, in one module so the contrast test can read them.
// Every fill that carries text declares its own on-* ink; Vuetify's automatic pick is
// white-biased (APCA) and lands under 4.5:1 on these mid-tone fills.
export const themes = {
    light: {
        dark: false,
        colors: {
            background: '#E8E9E3',
            surface: '#F4F5F1',
            'surface-bright': '#FAFBF8',
            'surface-light': '#E1E4DD',
            'surface-variant': '#1C2420',
            'on-surface-variant': '#F2F4ED',
            'on-background': '#1A241E',
            'on-surface': '#1A241E',
            primary: '#E7B643',
            'primary-darken-1': '#D3A329',
            'on-primary': '#1A140C',
            banner: '#2B2117',  // a dark warm bar with cream ink and a gold title
            'on-banner': '#FBF7F1',
            secondary: '#3F4C43',
            'secondary-darken-1': '#2E3931',
            'on-secondary': '#F2F4ED',
            error: '#8C3B2A',
            warning: '#A65200',
            info: '#2F6690',
            success: '#2A6B36',  // dark enough to carry AA as text on every light ground; #3D7A4A read 4.00:1 on surface-light
            'primary-text': '#916200',
            band: '#1C2420',
            'on-band': '#F2F4ED',
            hero: '#1C2420',
            'on-hero': '#F2F4ED',
            'band-muted': '#B9C4B6',
            tag: '#DCE1D8',
            'on-tag': '#3F4C43',
            win: '#1F63A6',
            loss: '#B31220',
            draw: '#A8A29A',
            'on-draw': '#1A241E',  // the light draw grey is the one light result fill that takes ink
            'tier-1': '#4E9A2E',
            'tier-2': '#94481A',
            'tier-3': '#4770BB',
            'tier-4': '#B3800E',
            'tier-5': '#1997A2',
            'tier-6': '#8B48CF',
            // A tier chip is a fill with a label on it, so each one names the ink that passes 4.5:1 on it
            'on-tier-1': '#1A241E',
            'on-tier-2': '#FBF7F1',
            'on-tier-3': '#FBF7F1',
            'on-tier-4': '#1A241E',
            'on-tier-5': '#1A241E',
            'on-tier-6': '#FBF7F1',
            'race-hu': '#0278E7',
            'race-oc': '#ED4952',
            'race-ne': '#00660C',
            'race-ud': '#62359C',
            // Medals name a metal, so the medal keeps its own gold beside the gold primary, and the rank numeral carries the rank
            'medal-gold': '#8F6B00',
            'medal-silver': '#6E7881',
            'medal-bronze': '#9A5B18',  // third place keeps the old bronze, now that primary is gold
            'heat-1': '#F0D49B',
            'heat-2': '#DBB155',
            'heat-3': '#B68B16',
            'heat-4': '#8E6800',
            'heat-5': '#664700',
        },
        variables: {
            'border-color': '#1A241E',
            'border-opacity': 0.2,
            'medium-emphasis-opacity': 0.78,  // 0.7 put every field label under 4.5:1 on the light surface
        },
    },
    dark: {
        dark: true,
        colors: {
            // Dark grounds are the public site's warm near-black, so both products share one ground
            background: '#080503',
            surface: '#0C0805',
            'surface-bright': '#16140F',
            'surface-light': '#1B1915',
            'surface-variant': '#D5DBD1',
            'on-surface-variant': '#1A241E',
            'on-background': '#E7EBE3',
            'on-surface': '#E7EBE3',
            primary: '#E7B643',
            'primary-darken-1': '#D3A329',
            'on-primary': '#1A140C',
            banner: '#1E1710',
            'on-banner': '#FBF7F1',
            secondary: '#C3CCC1',
            'secondary-darken-1': '#A7B1A4',
            'on-secondary': '#1A241E',
            error: '#FFB4AB',  // loss #DE6E52 sits next to it, so error carries a lighter, pinker red
            warning: '#F0A04B',
            info: '#7FB0DA',
            success: '#5FA870',  // inside the dark lightness band the chart-mark validator checks, still 4.62:1 or more as text
            'primary-text': '#E7B643',
            band: '#050301',
            'on-band': '#F2F4ED',
            hero: '#1E1710',  // lighter than the page, so the hero stands out from it
            'on-hero': '#F2F4ED',
            'band-muted': '#B9C4B6',
            tag: '#221F19',
            'on-tag': '#C3CCC1',
            win: '#4996F5',
            loss: '#E24947',
            draw: '#5E5B56',
            'tier-1': '#58A833',
            'tier-2': '#B0561F',
            'tier-3': '#6F92DA',
            'tier-4': '#BE8A00',
            'tier-5': '#16A3A6',
            'tier-6': '#A574E6',
            'race-hu': '#005BB5',
            'race-oc': '#B71824',
            'race-ne': '#2DA73D',
            'race-ud': '#9D6FE3',
            'medal-gold': '#E0B84A',
            'medal-silver': '#B9C2C8',
            'medal-bronze': '#D08B3C',
            'heat-1': '#5E4300',
            'heat-2': '#805D00',
            'heat-3': '#AA7E00',
            'heat-4': '#D3A329',
            'heat-5': '#F5CB70',
            // Vuetify picks white on these mid-tone fills, which is under 3.4:1; ink is 4.75:1 or more
            'on-error': '#1A241E',
            'on-info': '#1A241E',
            'on-success': '#1A241E',
            'on-warning': '#1A241E',
            'on-win': '#1A241E',
            'on-loss': '#1A140C',  // 4.59:1 on the true red; the stone ink reads 4.01:1
            'on-draw': '#FBF7F1',  // the dark draw grey is too deep for ink
            'on-tier-1': '#1A241E',
            'on-tier-2': '#FBF7F1',  // the one dark tier fill deep enough to need white; ink reads 3.19:1 on it
            'on-tier-3': '#1A241E',
            'on-tier-4': '#1A241E',
            'on-tier-5': '#1A241E',
            'on-tier-6': '#1A241E',
        },
        variables: {
            'border-color': '#E7EBE3',
            'border-opacity': 0.12,
            'medium-emphasis-opacity': 0.7,
        },
    },
};
